In [1]:
import torch

In [3]:
points = torch.tensor([[1,3],[4,2],[5,1]])

In [4]:
points.storage()

 1
 3
 4
 2
 5
 1
[torch.LongStorage of size 6]

In [6]:
points.storage()[1]

3

##  important properties: offset、stride、size

In [7]:
second_point = points[1]

In [8]:
second_point.size()

torch.Size([2])

In [9]:
second_point.storage_offset()

2

In [10]:
second_point.stride()

(1,)

In [11]:
# based on above observation, we can expect that changes in second_points will also occur on points
second_point[0] = 10

In [12]:
points

tensor([[ 1,  3],
        [10,  2],
        [ 5,  1]])

In [13]:
# a way to cut off this connection is clone()
clone_second_point = points[1].clone()

In [15]:
clone_second_point[0]=20

In [16]:
points

tensor([[ 1,  3],
        [10,  2],
        [ 5,  1]])

## transpose function a.t()

In [18]:
points_t = points.t()

In [20]:
#they have same storage
id(points.storage())==id(points_t.storage())

True

In [21]:
points.storage()

 1
 3
 10
 2
 5
 1
[torch.LongStorage of size 6]

In [22]:
#but different stride
points.stride(), points_t.stride()

((2, 1), (1, 2))

In [23]:
#and we can see that the transpose copy is always not contiguous
points.is_contiguous(), points_t.is_contiguous()

(True, False)

In [24]:
a = torch.randn(2,3)

In [25]:
a_t = a.t()

In [26]:
a.is_contiguous(),a_t.is_contiguous()

(True, False)

In [31]:
#using the function "contiguous()" will make the tensor make up a contiguous space in memory
points_t_con = points_t.contiguous()


In [30]:
points.stride()

(2, 1)

In [29]:
points_t.stride(),points_t.storage()

((1, 2),  1
  3
  10
  2
  5
  1
 [torch.LongStorage of size 6])

In [28]:
points_t_con.stride(), points_t_con.storage()

((3, 1),  1
  10
  5
  3
  2
  1
 [torch.LongStorage of size 6])

## storage in GPU

In [33]:
points_gpu = torch.tensor([[4,1],[5,3],[2,1]],device = 'cuda')

In [34]:
points_gpu = points.to(device='cuda')

In [35]:
points_gpu = 2 * points.to(device='cuda')

In [36]:
points_gpu = points_gpu + 4

## tensor with numpy

In [38]:
points = torch.ones(3,4)

In [39]:
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [40]:
points = torch.from_numpy(points_np)

In [41]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## torch to save and load

In [42]:
torch.save(points, '../DL with PyTorch/outpoints.t')

In [43]:
p_load = torch.load('../DL with PyTorch/outpoints.t')

In [44]:
p_load

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])