In [1]:
import torch


In [9]:
a = torch.ones(3,3)

In [10]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [11]:
a[1]

tensor([1., 1., 1.])

In [13]:
float(a[1][0])

1.0

In [14]:
a[2]=2.0

In [15]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.]])

In [16]:
p = torch.tensor([1,2,3,4])

In [17]:
p

tensor([1, 2, 3, 4])

In [19]:
p = torch.tensor([[1,2],[4,3],[5,7]])

In [20]:
p

tensor([[1, 2],
        [4, 3],
        [5, 7]])

In [21]:
p[1:]

tensor([[4, 3],
        [5, 7]])

In [23]:
p[1:,0]

tensor([4, 5])

In [25]:
p[None].shape

torch.Size([1, 3, 2])

## named tensor

In [56]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2,0.7,0.07])

In [57]:
batch_t = torch.randn(2,3,5,5)

In [59]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [61]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
img_weights = img_t * unsqueezed_weights
batch_weights = batch_t * unsqueezed_weights
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)

In [62]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [63]:
img_gray_weighted.shape, batch_gray_weighted.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [64]:
weights_named = torch.tensor([0.2,0.7,0.07], names=['channels'])

In [65]:
weights_named

tensor([0.2000, 0.7000, 0.0700], names=('channels',))

### refine_names用于给已经创建的tensor赋名

In [66]:
#img_t.shape = (3,5,5)
img_named = img_t.refine_names(...,'channels','rows','columns')

In [67]:
img_named.names

('channels', 'rows', 'columns')

In [68]:
#batch_t.shape = (2,3,5,5)
batch_named = batch_t.refine_names(...,'channels','rows','columns')
batch_named.names
#从这里也可以看出，命名是右对齐赋值

(None, 'channels', 'rows', 'columns')

### 用rename对已经命名的名称进行修改

In [75]:
#关键词命名法
batch_named = batch_named.rename(channels = 'channel', rows='row')
batch_named.names

(None, 'channel', 'row', 'columns')

In [76]:
batch_named = batch_named.rename(channel = 'channels', row='rows')
batch_named.names

(None, 'channels', 'rows', 'columns')

### align_as 调整尺寸和名字

In [82]:
weights_named.names, weights_named.shape

(('channels',), torch.Size([3]))

In [81]:
img_named.names, img_named.shape

(('channels', 'rows', 'columns'), torch.Size([3, 5, 5]))

In [78]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.names, weights_aligned.shape

(('channels', 'rows', 'columns'), torch.Size([3, 1, 1]))

In [83]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [84]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [85]:
for i in range(3):
    print(i)

0
1
2
